apiVersion: v1
kind: Service
metadata:
  labels:
    app: flink
    component: taskmanager
  name: flink-taskmanager
  namespace: intelligence
spec:
  ports:
    - name: rpc
      port: 6123
      protocol: TCP
      targetPort: 6123
    - name: query
      port: 6125
      protocol: TCP
      targetPort: 6125
    - name: metrics
      port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: flink
    component: taskmanager
  type: ClusterIP