apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: flink-example-app
    prometheus: mon-app
  name: flink-servicemonitor
  namespace: flink-example
spec:
  endpoints:
    - interval: 30s
      targetPort: 8090
  namespaceSelector:
    matchNames:
      - flink-example
  selector:
    matchLabels:
      app: flink-example-app