apiVersion: v1
kind: Service
metadata:
  labels:
    app: flink-example-app
    component: taskmanager
  name: flink-taskmanager
  namespace: flink-example
spec:
  ports:
    - name: data
      port: 6121
    - name: rpc
      port: 6122
    - name: metrics
      port: 8090
    - name: query
      port: 6125
  selector:
    app: flink-example-app
    component: taskmanager
  type: ClusterIP