apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flink-example-app
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink-example-app
        component: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: kamaji-dtr.tools.kmb.sonynei.net/raptor/kamaji-flink:1.0.20190905182522
        resources:
          limits:
            cpu: "12"
            memory: "4Gi"
          requests:
            cpu: "8"
            memory: "2Gi"
        args:
        - taskmanager
        ports:
        - containerPort: 6121
          name: data
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query
        - containerPort: 8090
          name: metrics
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: $(JOBMANAGER_SERVICE)
        - name: NUM_SLOTS
          value: "4"
